version: "3.3"

services:
  resume_builder_frontend:
    image: resume_builder_frontend
    container_name: resume_builder_frontend
    restart: always
    build:
        context: .
    ports:
      - "2756:3000"
    env_file:
    - ".env"
    command: sh -c "cd /app && serve -s build"
    networks:
      - frontend_default

networks:
  frontend_default:
    external: true